#!/usr/bin/env bash
# servers are the piece of software generating and serving HTML pages
# Install nginx on your web-01

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World" > /var/www/html/index.html'
service nginx restart
