#!/usr/bin/env bash
# Bash script that configure a ubuntu machine
# to create a custom 404 error page with the string "Ceci n'est pas une page"
# the page must return HTTP 404 error code

sudo apt update -y
sudo apt install nginx -y

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.github.com\/Jeyrio permanent;\n\terror_page 404 \/404.html;\n\tlocation \/404.html{\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-enabled/default

sudo service nginx restart
