#!/usr/bin/env bash
# Bash script that configure a ubuntu machine 
# to create a custom 404 error page with the string "Ceci n'est pas une page"
# the page must return HTTP 404 error code

sudo apt-get update -y
sudo apt-get install nginx -y
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sh -c "echo "Ceci n\'est pas une page" > /var/www/html/404.html"
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/Jeyrio permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
